[asdf]

[[asdf.plugins]]
name = "java"
versions = [
  "adoptopenjdk-11.0.26+4",
  "adoptopenjdk-17.0.14+7",
  "adoptopenjdk-21.0.6+7.0.LTS",
  "liberica-8u345+1",
]

[[asdf.plugins]]
name = "nodejs"
versions = [
  "14.17.1",
  "14.18.2",
  "22.14.0"
]

[[asdf.plugins]]
name = "python"
versions = [
  "2.7.18",
  "3.10.13",
  "3.12.3"
]
